apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-admin
spec:
  selector:
    app: pg-admin
  ports:
    - port: 8006
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
spec:
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
        - name: pg-admin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@example.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: 1234
          volumeMounts:
            - name: storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pg-admin-pvc