apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-db
  labels:
    type: local
    name: todo-db
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db-storage/todo-db
---
apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  ports:
    - port: 5432
  selector:
    app: todo-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-accounts-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: todo-db
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - image: "postgres:9.6.2"
          name: todo-db
          env:
            - name: POSTGRES_PASSWORD
              value: 'p@5tGr3s'
            - name: POSTGRES_USER
              value: 'user'
            - name: POSTGRES_DB
              value: 'todo'
          ports:
            - containerPort: 5432
              name: todo-db
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
           claimName: pg-todo-claim
