apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo
  name: todo
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: todo
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: biggo6/todo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: 'jdbc:postgresql://postgres:5432/postgresdb'
        - name: DB_USER
          value: 'postgres'
        - name: DB_PASS
          value: 'root'

